name: sample_pod_flutter
description: A new Flutter project with Serverpod.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  serverpod_flutter: ^1.0.1
  sample_pod_client:
    path: ../sample_pod_client


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

